# Build Directories
build:
  prepare_data: build/anything
  descriptive: build/descriptive

# Source Directories
source:
  prepare_data: source/anything
  descriptive: source/descriptive

# Switch to 'Yes' if any of the following softwares are required
git-lfs: No
Stata: No
R: No
Lyx: No
