Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['draw_data']
source = env['CONFIG']['global']['source']['draw_data']

env.BuildStata(target  = ['#%s/data.csv'       % build],
               source  = ['#%s/draw_data.do' % source],
               log_ext =  'draw_data')

env.Install('#release/lg', '#%s/data.csv' % build)
