Import('env')

data  = env['CONFIG']['global']['build']['data']
tables   = env['CONFIG']['global']['build']['tables']
source   = env['CONFIG']['global']['source']['tables']

targets = ["#%s/regressions-%s-%s.tex" %(tables, t, cslabel) for t in ['levels','logs'] for cslabel in ['state-clustering','no-clustering']]
env.BuildR(target  = targets,
           source  = ['#%s/concentration.R' % source, '#%s/dataset-prepared.fst'])

