"""Define a dictionary *project_paths* with path
definitions for the entire project.

This module is automatically generated by Waf, never change it!

If paths need adjustment, change them in the root wscript file.

"""

import os
import re


project_paths = {}
project_paths['IN_EXAMPLE'] = r'/Users/leviboxell/Desktop/template/source/analysis/example'
project_paths['MAKE_LIB'] = r'/Users/leviboxell/Desktop/template/lib/make/py'
project_paths['OUTPUT_DIR'] = r'/Users/leviboxell/Desktop/template/output'
project_paths['OUT_EXAMPLE'] = r'/Users/leviboxell/Desktop/template/output/analysis/example'
project_paths['PROJECT_ROOT'] = r'/Users/leviboxell/Desktop/template'


def project_paths_join(key, *args):
    """Given input of a *key* in the *project_paths* dictionary and a number
    of path arguments *args*, return the joined path constructed by:

    .. code-block:: python

            os.path.join(project_paths[key], *args)

    """

    return os.path.join(project_paths[key], *args)


def project_paths_join_latex(key, *args):
    """Given input of a *key* in the *project_paths* dictionary and a number
    of path arguments *args*, return the joined path constructed by::

            os.path.join(project_paths[key], *args)

    and backslashes replaced by forward slashes.

    """

    p = project_paths_join(key, *args)
    p = p.replace('\\', '/')
    p = re.sub('/+', '/', p)

    return p
