Import('env')

env.BuildStata(target = ['#output/analysis/plot.eps',
                         '#output/analysis/table.txt'],
               source = ['#source/analysis/analysis.do',
                         '#output/data/data.txt'])