#! python

def build(ctx):
	ctx(
		features = 'run_r_script',
		source = 'sample_plots.R',
		deps = [ctx.path_to(ctx, 'OUT_DATA', 'data.rds')],
		target = [
			ctx.path_to(ctx, 'OUT_EXAMPLE', 'plot.pdf'),
			ctx.path_to(ctx, 'OUT_EXAMPLE', 'appendix_plot.pdf'),
			ctx.path_to(ctx, 'OUT_EXAMPLE', 'online_plot.pdf')
			],
		name = 'run_analysis_example'
	)


