Import('env')

env.BuildLyx(target = '#%s/slides.pdf'  % env['PATHS']['build']['talk'], 
             source = ['#%s/slides.lyx' % env['PATHS']['source']['talk']])

env.Install('#release', '#%s/' % env['PATHS']['build']['talk'])