Import('*')

talk_dependencies = ['#source/talk/slides.lyx']
talk_targets = ['#output/talk/slides.pdf', '#output/talk/make.log']
env.Command(
	target = talk_targets,
	source = talk_dependencies,
	action = 'lyx -e pdf2 source/talk/slides.lyx > output/talk/make.log && mv source/talk/slides.pdf output/talk/slides.pdf')
