Import('env')
import yaml
PATHS = yaml.load(open("../../constants.yaml", 'rU'))

env.BuildLyx(target = '#%s/slides.pdf'  % PATHS['build']['talk'], 
             source = ['#%s/slides.lyx' % PATHS['source']['talk']])

env.Install('#release', '#%s/' % PATHS['build']['talk'])
