Import('env')

import gslab_scons as gs

build = 'build/anything'
source = 'source/anything'

gs.build_anything(target = ['#%s/data.txt'    % build],
                  source = ['#%s/create_data.do' % source],
                  action = 'stata-mp -e source/anything/create_data.do',
                  env    = env,
                  origin_log_file = 'create_data.log')

gs.build_anything(target = ['#%s/data_1.txt'    % build],
                  source = ['#%s/create_data_1.do' % source],
                  action = 'stata-mp -e source/anything/create_data_1.do',
                  env    = env,
                  log_ext = '1',
                  origin_log_file = 'create_data_1.log')
