Import('*')


env.Command(
	target = '#output/paper/paper.pdf',
	source = ['#source/paper/paper.lyx', '#output/analysis/plot.eps'],
	action = '''lyx -e pdf2 source/paper/paper.lyx > \
				output/paper/sconscript.log &&  \
				mv source/paper/paper.pdf output/paper/paper.pdf'''
	)

env.Command(
	target = '#output/paper/online_appendix.pdf',
	source = ['#source/paper/online_appendix.lyx', 
				'#output/analysis/plot.eps'],
	action = '''lyx -e pdf2 source/paper/online_appendix.lyx >> \
				output/paper/sconscript.log && \
				mv source/paper/online_appendix.pdf \
				output/paper/online_appendix.pdf'''
	)
