Import('env')
import yaml
PATHS  = yaml.load(open("../../constants.yaml", 'rU'))
build  = PATHS['build']['paper']
source = PATHS['source']['paper']

env.BuildLyx(target = ['#%s/paper.pdf' % build],
             source = ['#%s/paper.lyx' % source])

env.BuildLyx(target = ['#%s/online_appendix.pdf' % build], 
             source = ['#%s/online_appendix.lyx' % source])

env.BuildLyx(target = ['#%s/text.pdf' % build],
             source = ['#%s/text.lyx' % source])

env.BuildLyx(target = ['#%s/ondeck.pdf' % build], 
             source = ['#%s/ondeck.lyx' % source])

env.Install('#release', '#%s/' % build)
