Import('env')
import gslab_scons as gs

build  = env['CONFIG']['global']['build']['prepare_data']
source = env['CONFIG']['global']['source']['prepare_data']
dbox   = env['CONFIG']['global']['dropbox']['ra_practice_task']

# env.BuildPython(target  = ['#%s/data.txt'       % build],
#                 source  = ['#%s/create_data.py' % source],
#                 log_ext =  'create_data')

env.BuildStata(target  = ['#%s/data_stata.txt'  % build],
               source  = ['#%s/create_data.do'  % source],
               log_ext = 'create_data_stata')

env.BuildR(target  = ['#%s/data_r.txt'     % build],
           source  = ['#%s/create_data.r'  % source],
           log_ext = 'create_data_r')

# env.BuildMatlab(target  = ['#%s/data.txt'        % build],
#                 source  = ['#%s/create_data.m'   % source],
#                 log_ext =  'create_data')

# # Invalid syntax for Windows.
gs.build_anything(target  = ['#%s/data.txt'            % build], 
                  source  = [''],
                  action  = 'rclone copy gsbox:%s %s'  % (dbox, build),
                  log_ext = 'load_dropbox_data',
                  env     = env)

env.Install('#release/lg', '#%s/data.txt' % build)
