Import('env')

build  = env['PATHS']['build']['prepare_data']
source = env['PATHS']['source']['prepare_data']

env.BuildPython(target  = ['#%s/data.txt'       % build],
                source  = ['#%s/create_data.py' % source],
                log_ext =  'create_data')

# env.BuildStata(target  = ['#%s/data.txt'       % build],
#                source  = ['#%s/create_data.do' % source],
#                log_ext =  'create_data')

# env.BuildR(target  = ['#%s/data.txt'      % build],
#            source  = ['#%s/create_data.r' % source],
#            log_ext =  'create_data')

# env.BuildMatlab(target  = ['#%s/data.txt'        % build],
#                 source  = ['#%s/create_data.m'   % source],
#                 log_ext =  'create_data')

env.Install('#release/lg', '#%s/data.txt' % build)
