Import('env')

build  = env['paths_global']['build']['descriptive']
source = env['paths_global']['source']['descriptive']
data   = env['paths_global']['build']['prepare_data']

env.BuildPython(target  = ['#%s/plot.eps'       % build,
                           '#%s/table.txt'      % build],
                source  = ['#%s/descriptive.py' % source,
                           '#%s/data.txt'       % data],
                log_ext = 'descriptive')

env.Install('#release', '#%s/' % build)
