# Build Directories
build:
  prepare_data: build/prepare_data
  descriptive: build/descriptive

# Source Directories
source:
  prepare_data: source/prepare_data
  descriptive: source/descriptive

# Required softwares
git-lfs: No
Stata: No
R: No
Lyx: No
