# Build Directories
build:
  prepare_data: build/prepare_data
  descriptive: build/descriptive

# Source Directories
source:
  prepare_data: source/prepare_data
  descriptive: source/descriptive

# Switch to 'Yes' if any of the following softwares are required
git-lfs: Yes
Latex: No
Lyx: No
Matlab: No
R: No
Stata: No
