# Build Directories
build:
  prepare_data: build/prepare_data
  descriptive: build/descriptive

# Source Directories
source:
  prepare_data: source/prepare_data
  descriptive: source/descriptive

# Switch to 'Yes' if any of the following softwares are required
prereq_git-lfs: Yes
prereq_Latex: No
prereq_Lyx: No
prereq_Matlab: No
prereq_R: No
prereq_Stata: No
