# Build Directories
build:
  prepare_data: build/prepare_data
  descriptive: build/descriptive

# Source Directories
source:
  prepare_data: source/prepare_data
  descriptive: source/descriptive

Stata: yaml, preliminaries, matrix_to_txt
R: yaml
Matlab: yaml
