Import('*')
import os

env.Command(
	target = '#build/data/data.txt',  
	source = 'build.R',
	action = 'Rscript source/data/build.R > build/data/sconscript.log'
	)

env.Install('#release', '#build/data/data.txt')