Import('*')
import os

env.Command(
	target = '#build/data/data.txt',  
	source = 'build.R',
	action = 'Rscript source/data/build.R > build/data/sconscript.log'
	)

env.Install('#output/data/', '#build/data/data.txt')
